services:
  # ZOOKEEPER

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # KAFKA

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  # POSTGRES 
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # AIRFLOW METADATA DB

  airflow-db:
    image: postgres:16
    container_name: airflow_db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data


  # SPARK MASTER
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8082:8080"
      - "7077:7077"
    networks:
      - data-net


  # SPARK WORKER

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - data-net

  # AIRFLOW WEBSERVER
  airflow-webserver:
    image: apache/airflow:3.2.2
    container_name: airflow_webserver
    depends_on:
      - airflow-db
      - spark-master
      - kafka
    restart: always
    ports:
      - "8081:8080"
    command: api-server
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 120
      PYTHONPATH: /opt/project/src
    volumes:
      - ./:/opt/project
      - ./orchestration/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs


  # AIRFLOW SCHEDULER
  airflow-scheduler:
    image: apache/airflow:3.2.2
    container_name: airflow_scheduler
    depends_on:
      - airflow-db
      - spark-master
      - kafka
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/project/src
    volumes:
      - ./:/opt/project
      - ./orchestration/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler

# AIRFLOW TRIGGER
  airflow-triggerer:
    image: apache/airflow:3.2.2
    container_name: airflow_triggerer
    restart: always
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/project/src
    volumes:
      - ./:/opt/project
      - ./orchestration/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: triggerer


# AIRFLOW PROCESSOR
  airflow-dag-processor:
    image: apache/airflow:3.2.2
    container_name: airflow_dag_processor
    restart: always
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/project/src
    volumes:
      - ./:/opt/project
      - ./orchestration/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: dag-processor

volumes:
  postgres_data:
  airflow_postgres_data:

networks:
  data-net:
